<div style="text-align: center;">
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/1280px-Pandas_logo.svg.png" alt="Pandas Logo" width="500">
    <p style="font-size: 50px; font-weight: bold;">Pengenalan Pandas</p>
    <p style="font-size: 50px; font-weight: normal;">Intern BCC 2026</p>
</div>

# Pandas 🐼

### 🎯 Tujuan Notebook Ini
Setelah selesai, (minimal) bisa:
- memahami struktur data utama (Pandas) dan kapan dipakai
- menulis kode yang rapi untuk kebutuhan data science dasar (cleaning, transform, ringkas data)
- tahu *pitfall* yang sering bikin bingung (dtype, indexing, missing values, dsb.)

## Import Pandas

In [1]:
# !pip install pandas

In [2]:
import pandas as pd

In [3]:
# pd.set_option("display.max_columns", None)
# pd.set_option("display.max_rows", None)

## Read CSV

Di workshop ini kita pakai dataset **NYC Taxi Trips (sample)** karena **cukup "kaya fitur"** untuk latihan Pandas:

- ✅ `datetime` → `pickup`, `dropoff`
- ✅ numerik → `distance`, `fare`, `tip`, `total`
- ✅ kategori/teks → `payment`, `pickup_zone`, `pickup_borough`, dll.
- ✅ ada missing value alami (buat latihan data cleaning)

Sumber dataset: repository **seaborn-data** (`taxis.csv`).

In [81]:
import os

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/taxis.csv"
local_path = "taxis.csv"

if os.path.exists(local_path):
    data = pd.read_csv(local_path)
else:
    data = pd.read_csv(url)

data.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   object
 1   dropoff          6433 non-null   object
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: float64(5), int64(1), object(8)
memory usage: 703.7+ KB

In [83]:
# Parse kolom datetime (biar enak dipakai untuk analisis waktu)
data["pickup"] = pd.to_datetime(data["pickup"])
data["dropoff"] = pd.to_datetime(data["dropoff"])

data.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [5]:
# Cek cepat ukuran & kolom yang tersedia
print("Shape:", data.shape)
print("Columns:", list(data.columns))

Shape: (6433, 14)
Columns: ['pickup', 'dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls', 'total', 'color', 'payment', 'pickup_zone', 'dropoff_zone', 'pickup_borough', 'dropoff_borough']

### Tips `read_csv` untuk Data Science (Opsional tapi berguna)

Kalau dataset mulai besar, 2 trik yang sering dipakai:
1) **`parse_dates`** supaya kolom waktu langsung jadi datetime  
2) **`dtype`** untuk hemat memori (misal kategori pakai `category`)

> Catatan: ini contoh pola, tidak wajib dipakai untuk dataset kecil.

In [6]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/taxis.csv"
local_path = "taxis.csv"

dtype_map = {
    "passengers": "int16",
    "color": "category",
    "payment": "category",
    "pickup_borough": "category",
    "dropoff_borough": "category",
}

if os.path.exists(local_path): 
    data_opt = pd.read_csv(local_path, dtype=dtype_map, parse_dates=["pickup", "dropoff"])
else:
    data_opt = pd.read_csv(url, dtype=dtype_map, parse_dates=["pickup", "dropoff"])

data_opt.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

## DataFrame

Bayangin **DataFrame** itu kayak **tabel**:

| index | pickup_zone        | passengers | total |
|------:|--------------------|-----------:|------:|
| 0     | Midtown Center     | 1          | 14.5  |
| 1     | JFK Airport        | 2          | 38.0  |
| 2     | Upper East Side    | 1          | 12.2  |

**Intinya:**
- baris = observasi/record
- kolom = fitur/variabel
- tiap kolom punya tipe data (angka, kategori, datetime, dll)

> Tips: DataFrame ini 'rumah' utama kita ketika ngolah data di Pandas.

In [7]:
data

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

### **Membuat DataFrame Secara Manual**

Kadang kita butuh bikin DataFrame kecil untuk demo / simulasi data.

Contoh: **menu & stok kedai kopi ☕**

- **Key** → nama kolom  
- **Value** → isi kolom (list)  
- **Index** → default 0..n-1 (bisa diganti)

<img src="https://media.tenor.com/2roX3uxz_68AAAAM/coffee.gif" alt="coffee" width="180">

In [8]:
dict_data = {
    "Menu": ["Kopi Susu", "Espresso", "Matcha Latte", "Croissant"],
    "Kategori": ["Drink", "Drink", "Drink", "Food"],
    "Harga": [18000, 15000, 22000, 17000],
    "Stok": [25, 40, 18, 12]
}

manual_df = pd.DataFrame(dict_data)
manual_df

           Menu Kategori  Harga  Stok
0     Kopi Susu    Drink  18000    25
1      Espresso    Drink  15000    40
2  Matcha Latte    Drink  22000    18
3     Croissant     Food  17000    12

### **Mengubah Label Kolom dan Indeks pada DataFrame**

Tujuannya biar **lebih jelas** & enak dibaca.

- `rename(columns=...)` → ganti nama kolom
- `rename(index=...)` → ganti label index (baris)

<img src="https://media1.tenor.com/m/LWznTFcFM6EAAAAd/typing.gif" alt="typing" width="170">

In [9]:
# Ganti nama kolom
manual_df = manual_df.rename(columns={"Harga": "Harga_Rp"})

# Ganti label index (contoh: kasih label khusus untuk item tertentu)
manual_df = manual_df.rename(index={3: "Snack Favorit"})

manual_df

                       Menu Kategori  Harga_Rp  Stok
0                 Kopi Susu    Drink     18000    25
1                  Espresso    Drink     15000    40
2              Matcha Latte    Drink     22000    18
Snack Favorit     Croissant     Food     17000    12

### **Menambahkan Kolom Baru pada DataFrame**

Kita bisa menambah informasi baru tanpa mengubah data lama.

Contoh: bikin flag **Promo** (True jika harga <= 18k).

In [10]:
manual_df["Promo"] = manual_df["Harga_Rp"] <= 18000
manual_df

                       Menu Kategori  Harga_Rp  Stok  Promo
0                 Kopi Susu    Drink     18000    25   True
1                  Espresso    Drink     15000    40   True
2              Matcha Latte    Drink     22000    18  False
Snack Favorit     Croissant     Food     17000    12   True

In [11]:
print(len(manual_df))

4

#### **Menambah Baris Baru pada DataFrame**

Ada banyak cara. Untuk pemula, salah satu yang gampang:

- pakai `.loc[len(df)]` → tambah baris di index paling bawah

> Kenapa `len(df)`? karena index terakhir = jumlah baris saat ini (0..len-1).

In [12]:
manual_df.loc[len(manual_df)] = ["Americano", "Drink", 16000, 30, True]
manual_df

                       Menu Kategori  Harga_Rp  Stok  Promo
0                 Kopi Susu    Drink     18000    25   True
1                  Espresso    Drink     15000    40   True
2              Matcha Latte    Drink     22000    18  False
Snack Favorit     Croissant     Food     17000    12   True
4                 Americano    Drink     16000    30   True

In [13]:
# Contoh copy kolom (misal buat backup sebelum transform)
manual_df["Menu_copy"] = manual_df["Menu"]
manual_df

                       Menu Kategori  Harga_Rp  Stok  Promo     Menu_copy
0                 Kopi Susu    Drink     18000    25   True     Kopi Susu
1                  Espresso    Drink     15000    40   True      Espresso
2              Matcha Latte    Drink     22000    18  False  Matcha Latte
Snack Favorit     Croissant     Food     17000    12   True     Croissant
4                 Americano    Drink     16000    30   True     Americano

## **Series dalam Pandas**

Series dalam Pandas adalah struktur data satu dimensi yang mirip dengan **array** atau **kolom dalam tabel**.  
Series dapat menyimpan berbagai tipe data, seperti **integer, float, string, atau objek Python**.  

Perbedaan utama antara **Series** dan **array biasa** adalah bahwa setiap elemen dalam Series memiliki **index** yang menyertainya. 🔢✨  

### **Komponen dalam Series:**
1. **Data** → Nilai-nilai yang tersimpan dalam Series, bisa berupa angka, teks, atau tipe data lainnya.
2. **Index** → Label unik untuk setiap elemen dalam Series.  
   Secara default, indeks dimulai dari **0 hingga n** (jumlah elemen - 1).

In [14]:
# Mengambil Series dari salah satu kolom DataFrame (contoh: Harga)
harga_series = manual_df["Harga_Rp"]

print("Tipe data:", type(harga_series))
harga_series

Tipe data: <class 'pandas.core.series.Series'>

0                18000
1                15000
2                22000
Snack Favorit    17000
4                16000
Name: Harga_Rp, dtype: int64

### **Membuat Series Secara Manual**  

Untuk memahami lebih lanjut, kita bisa membuat **Series** secara manual menggunakan **List** di Python.  

Series yang dibuat dari **List** akan secara otomatis memiliki **indeks numerik** yang dimulai dari **0 hingga n** (jumlah elemen - 1).

In [92]:
list_data = ["Kopi Susu", "Espresso", "Matcha Latte", "Croissant"]
manual_series = pd.Series(list_data, name="Menu")
manual_series

0       Kopi Susu
1        Espresso
2    Matcha Latte
3       Croissant
Name: Menu, dtype: object

## Data Exploration Using Pandas

### **Menampilkan Baris Teratas dengan `head()`**  

Dalam analisis data, sering kali kita ingin melihat **cuplikan awal** dari DataFrame untuk memahami struktur dan isinya.  
Pandas menyediakan metode `.head(n)`, yang digunakan untuk menampilkan **n baris pertama** dari DataFrame.  

nilai default n = 5

In [107]:
data.head(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
7,2019-03-22 12:47:13,2019-03-22 12:58:17,0,1.40,8.5,0.00,0.0,11.80,yellow,NaN,Murray Hill,Flatiron,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.0,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
9,2019-03-08 16:18:37,2019-03-08 16:26:57,1,1.52,8.0,1.00,0.0,13.30,yellow,credit card,Lincoln Square East,Central Park,Manhattan,Manhattan

### Tail

### **Menampilkan Baris Terbawah dengan `tail()`**  

Saat bekerja dengan data, kita tidak hanya perlu melihat bagian awalnya, tetapi juga **baris-baris terakhir** untuk memahami struktur data secara keseluruhan.  
Pandas menyediakan metode `.tail(n)`, yang digunakan untuk menampilkan **n baris terakhir** dari DataFrame.  

nilai default n = 5

In [17]:
data.tail()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [18]:
# data

### **Mengetahui Dimensi Data dengan `shape`**  

Saat bekerja dengan data, penting untuk mengetahui **berapa banyak baris dan kolom** yang ada dalam DataFrame.  
Pandas menyediakan atribut `.shape`, yang mengembalikan **_tuple_ (n, m)**, di mana:  

- **n** → Jumlah baris dalam DataFrame.  
- **m** → Jumlah kolom dalam DataFrame.

In [19]:
data.shape

(6433, 14)

### **Menampilkan Informasi Detail Data dengan `info()`**  

Dalam analisis data, kita perlu memahami struktur dataset yang kita gunakan.  
Pandas menyediakan metode `.info()`, yang memberikan **ringkasan detail** tentang setiap **kolom** dalam DataFrame.  

#### **🔹 Apa Saja yang Ditampilkan oleh `.info()`?**  
- **Jumlah total baris dan kolom** dalam DataFrame.  
- **Nama setiap kolom** dan jumlah nilai yang tidak kosong (**non-null values**).  
- **Tipe data** dari setiap kolom (misalnya: `int64`, `float64`, `object` untuk teks).  
- **Penggunaan memori** dari DataFrame.

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

### **Mendapatkan Ringkasan Statistik dengan `describe()`**  

Saat menganalisis data, kita sering ingin melihat **ringkasan statistik** untuk memahami distribusi dan karakteristik data numerik.  
Pandas menyediakan metode `.describe()`, yang memberikan **statistik deskriptif** untuk semua kolom numerik dalam DataFrame.  

#### **🔹 Apa Saja yang Ditampilkan oleh `.describe()`?**  
- **count** → Jumlah total baris yang memiliki nilai (bukan NaN).  
- **mean** → Nilai rata-rata dari kolom numerik.  
- **std** → **Standar deviasi**, mengukur seberapa tersebar datanya.  
- **min** → Nilai terkecil dalam kolom.  
- **25%** → **Kuartil pertama (Q1)** atau presentil bawah (25% data lebih kecil dari ini).  
- **50%** → **Median (Q2)** atau nilai tengah dalam dataset.  
- **75%** → **Kuartil ketiga (Q3)** atau presentil atas (75% data lebih kecil dari ini).  
- **max** → Nilai terbesar dalam kolom.

In [21]:
# Menggunakan Describe
data.describe()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total
count,6433,6433,6433.000000,6433.000000,6433.000000,6433.00000,6433.000000,6433.000000
mean,2019-03-16 08:31:28.514223616,2019-03-16 08:45:49.491217408,1.539251,3.024617,13.091073,1.97922,0.325273,18.517794
min,2019-02-28 23:29:03,2019-02-28 23:32:35,0.000000,0.000000,1.000000,0.00000,0.000000,1.300000
25%,2019-03-08 15:50:34,2019-03-08 16:12:51,1.000000,0.980000,6.500000,0.00000,0.000000,10.800000
50%,2019-03-15 21:46:58,2019-03-15 22:06:44,1.000000,1.640000,9.500000,1.70000,0.000000,14.160000
75%,2019-03-23 17:41:38,2019-03-23 17:51:56,2.000000,3.210000,15.000000,2.80000,0.000000,20.300000
max,2019-03-31 23:43:45,2019-04-01 00:13:58,6.000000,36.700000,150.000000,33.20000,24.020000,174.820000
std,NaN,NaN,1.203768,3.827867,11.551804,2.44856,1.415267,13.815570

In [22]:
data

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [23]:
# Contoh ringkas ambil angka penting (biar kebiasaan ngintip data)
print("Rata-rata jarak (mile):", data["distance"].mean())
print("Rata-rata total bayar:", data["total"].mean())
print("Jumlah trip:", data.shape[0])

Rata-rata jarak (mile): 3.024616819524328
Rata-rata total bayar: 18.517794186227267
Jumlah trip: 6433

### **Melihat Nilai Unik dalam Kolom dengan `unique()`**  

Metode `.unique()` digunakan untuk melihat **daftar nilai unik** dalam suatu kolom pada DataFrame.  
Ini berguna untuk memahami variasi data dalam kategori tertentu.

In [24]:
data["payment"].unique()

array(['credit card', 'cash', nan], dtype=object)

### **Melihat Jumlah Nilai Unik dalam Kolom dengan `nunique()`**  

Metode `.nunique()` digunakan untuk mengetahui **berapa banyak nilai unik** yang terdapat dalam suatu kolom.  
Ini berguna untuk memahami keragaman data dalam kategori tertentu.

In [25]:
data["payment"].nunique()

2

### **Melihat Jumlah Data untuk Setiap Nilai Unik dengan `value_counts()`**  

Dalam analisis data, kita sering ingin mengetahui **berapa kali setiap nilai unik muncul** dalam suatu kolom.  
Pandas menyediakan metode `.value_counts()`, yang menghitung frekuensi kemunculan setiap kategori dalam suatu kolom.

In [26]:
data["payment"].value_counts(dropna=False)

payment
credit card    4577
cash           1812
NaN              44
Name: count, dtype: int64

### **Seleksi Data dalam DataFrame**  

Untuk mengambil nilai dari baris atau kolom tertentu, kita bisa menggunakan **seleksi data**.

#### **Seleksi Data dengan `[]` (Indexing Sederhana)**  

Cara paling sederhana untuk mengambil data dari suatu kolom adalah dengan menggunakan **bracket notation** `[ ]`.  
Namun, metode ini hanya bisa digunakan untuk **mengakses kolom**, bukan baris tertentu.

In [27]:
# Mengambil semua data pada sebuah kolom tertentu dalam bentuk DataFrame
data[["payment"]]

          payment
0     credit card
1            cash
2     credit card
3     credit card
4     credit card
...           ...
6428  credit card
6429  credit card
6430         cash
6431  credit card
6432  credit card

[6433 rows x 1 columns]

In [28]:
# Mengambil semua data pada sebuah kolom tertentu dalam bentuk Series
data["total"]

0       12.95
1        9.30
2       14.16
3       36.95
4       13.40
        ...
6428     6.36
6429    58.80
6430    17.30
6431     6.80
6432    20.16
Name: total, Length: 6433, dtype: float64

In [29]:
# Mengambil semua data pada kolom tertentu
data[["pickup", "dropoff", "passengers", "distance", "total"]]

                  pickup             dropoff  passengers  distance  total
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60  12.95
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   9.30
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37  14.16
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  36.95
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16  13.40
...                  ...                 ...         ...       ...    ...
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   6.36
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.80
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  17.30
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.80
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  20.16

[6433 rows x 5 columns]

### **Seleksi Data dengan `loc`**  

Metode `.loc[]` digunakan untuk mengambil data berdasarkan **label** baris dan kolom.  
Dengan ini, kita bisa memilih **baris tertentu**, **kolom tertentu**, atau keduanya sekaligus.

In [30]:
# Mengambil baris index 0 hingga 5 pada semua kolom
data.loc[0:5]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan

In [31]:
# Mengambil semua baris pada kolom tertentu
data.loc[:, ["pickup_zone", "dropoff_zone"]]

                pickup_zone                      dropoff_zone
0           Lenox Hill West               UN/Turtle Bay South
1     Upper West Side South             Upper West Side South
2             Alphabet City                      West Village
3                 Hudson Sq                    Yorkville West
4              Midtown East                    Yorkville West
...                     ...                               ...
6428      East Harlem North              Central Harlem North
6429                Jamaica  East Concourse/Concourse Village
6430    Crown Heights North                    Bushwick North
6431          East New York      East Flatbush/Remsen Village
6432            Boerum Hill                   Windsor Terrace

[6433 rows x 2 columns]

In [32]:
# Mengambil range index baris tertentu pada kolom tertentu menggunakan list
data.loc[10:15, ["pickup_zone", "distance", "total"]]

                 pickup_zone  distance  total
10         LaGuardia Airport      3.90  17.80
11     Upper West Side South      1.53  12.96
12               Murray Hill      1.05  11.30
13       Lincoln Square West      1.75  13.80
14  Financial District North      2.90  14.80
15     Upper West Side North      2.09  16.80

In [33]:
data

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [34]:
# Mengambil range index baris tertentu pada range kolom tertentu
data.loc[0:5, "pickup":"distance"]

               pickup             dropoff  passengers  distance
0 2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16
5 2019-03-11 10:37:23 2019-03-11 10:47:31           1      0.49

In [35]:
# Mengambil baris index tertentu dan pada kolom tertentu menggunakan list
data.loc[[1, 5, 20, 42], ["pickup_zone", "passengers", "total"]]

                     pickup_zone  passengers   total
1          Upper West Side South           1    9.30
5      Times Sq/Theatre District           1   12.96
20  Penn Station/Madison Sq West           1   11.84
42                           NaN           1  100.38

**Latihan**

Tampilkan data pada baris ke **100 - 110** untuk kolom:
- `pickup_zone`
- `total`

### **Seleksi Data dengan `iloc`**  

Metode `.iloc[]` digunakan untuk mengambil data berdasarkan **posisi indeks integer** dalam DataFrame.  
Cara penggunaannya mirip dengan `.loc[]`, tetapi menggunakan **angka** sebagai referensi baris dan kolom.

In [37]:
# Mengambil range baris tertentu pada range kolom tertentu
data.iloc[1:5, 0:4]

               pickup             dropoff  passengers  distance
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16

In [38]:
# Mengambil semua baris pada kolom tertentu
data.iloc[:, [0, 5]]

                  pickup   tip
0    2019-03-23 20:21:09  2.15
1    2019-03-04 16:11:55  0.00
2    2019-03-27 17:53:01  2.36
3    2019-03-10 01:23:59  6.15
4    2019-03-30 13:27:42  1.10
...                  ...   ...
6428 2019-03-31 09:51:53  1.06
6429 2019-03-31 17:38:00  0.00
6430 2019-03-23 22:55:18  0.00
6431 2019-03-04 10:09:25  0.00
6432 2019-03-13 19:31:22  3.36

[6433 rows x 2 columns]

**Latihan**

Tampilkan data pada baris ke **30 - 50**, pada kolom:
- `pickup`
- `total`

#### Perbedaan `.loc[]` vs `.iloc[]` di Pandas

| **Fitur**           | **.loc[]**                                | **.iloc[]**                        |
|---------------------|--------------------------------------|----------------------------------|
| **Berdasarkan**     | Label indeks (bisa angka atau string) | Posisi indeks (hanya angka)     |
| **Batas atas slicing** | **Inklusif** (batas atas termasuk) | **Eksklusif** (batas atas tidak termasuk) |
| **Bisa pakai string?** | ✅ Bisa | ❌ Tidak bisa |
| **Bisa pakai angka?** | ✅ Bisa (jika label indeks angka) | ✅ Bisa (karena posisi selalu angka) |

#### **Seleksi Data dengan Index Boolean**  

Kita bisa menggunakan `.loc[]` atau `[]` untuk melakukan **Boolean Indexing**, yaitu menyeleksi data berdasarkan kondisi tertentu.

In [40]:
data.head(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
7,2019-03-22 12:47:13,2019-03-22 12:58:17,0,1.40,8.5,0.00,0.0,11.80,yellow,NaN,Murray Hill,Flatiron,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.0,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
9,2019-03-08 16:18:37,2019-03-08 16:26:57,1,1.52,8.0,1.00,0.0,13.30,yellow,credit card,Lincoln Square East,Central Park,Manhattan,Manhattan

In [95]:
data["distance"] < 1

0       False
1        True
2       False
3       False
4       False
        ...
6428     True
6429    False
6430    False
6431    False
6432    False
Name: distance, Length: 6433, dtype: bool

In [42]:
data[(data["payment"] == "cash")]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.0,0.0,9.3,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.0,17.8,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.0,0.0,13.8,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.0,0.0,14.8,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.0,0.0,16.8,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6420,2019-03-16 15:39:23,2019-03-16 15:46:18,2,1.20,7.0,0.0,0.0,7.8,green,cash,Central Harlem,Upper West Side North,Manhattan,Manhattan
6422,2019-03-22 20:17:35,2019-03-22 20:36:07,1,4.02,16.0,0.0,0.0,17.3,green,cash,Washington Heights South,Spuyten Duyvil/Kingsbridge,Manhattan,Bronx
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.0,0.0,0.0,9.3,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.0,0.0,20.0,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.0,0.0,17.3,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn

In [43]:
# Boolean mask → struktur 1 dimensi True/False
filter_jarak_pendek = data["distance"] < 1
filter_jarak_pendek

0       False
1        True
2       False
3       False
4       False
        ...
6428     True
6429    False
6430    False
6431    False
6432    False
Name: distance, Length: 6433, dtype: bool

In [44]:
# Ambil baris yang memenuhi kondisi
data[filter_jarak_pendek]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
21,2019-03-25 23:05:54,2019-03-25 23:11:13,1,0.80,5.5,2.30,0.0,11.60,yellow,credit card,Penn Station/Madison Sq West,Murray Hill,Manhattan,Manhattan
29,2019-03-06 08:09:03,2019-03-06 08:27:11,1,0.92,12.0,0.00,0.0,15.30,yellow,cash,UN/Turtle Bay South,Garment District,Manhattan,Manhattan
31,2019-03-01 02:55:55,2019-03-01 02:57:59,3,0.74,4.0,0.00,0.0,7.80,yellow,cash,Clinton East,West Chelsea/Hudson Yards,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6393,2019-03-10 18:33:13,2019-03-10 19:32:38,1,0.00,71.2,0.00,0.0,72.00,green,credit card,Parkchester,Flatbush/Ditmas Park,Bronx,Brooklyn
6409,2019-03-21 17:46:43,2019-03-21 17:50:46,1,0.70,5.0,0.00,0.0,6.80,green,cash,Bushwick South,Bedford,Brooklyn,Brooklyn
6415,2019-03-03 08:42:49,2019-03-03 08:46:55,1,0.89,5.0,0.00,0.0,5.80,green,cash,Washington Heights South,Washington Heights South,Manhattan,Manhattan
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,5.80,green,credit card,Central Park,Upper West Side North,Manhattan,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan

In [45]:
# Contoh kondisi gabungan: jarak < 1 mile DAN tip = 0
filter_no_tip = data["tip"] == 0
data[filter_jarak_pendek & filter_no_tip]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.0,0.0,9.3,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
29,2019-03-06 08:09:03,2019-03-06 08:27:11,1,0.92,12.0,0.0,0.0,15.3,yellow,cash,UN/Turtle Bay South,Garment District,Manhattan,Manhattan
31,2019-03-01 02:55:55,2019-03-01 02:57:59,3,0.74,4.0,0.0,0.0,7.8,yellow,cash,Clinton East,West Chelsea/Hudson Yards,Manhattan,Manhattan
60,2019-03-01 22:49:54,2019-03-01 22:53:32,1,0.90,5.0,0.0,0.0,6.3,yellow,credit card,East Harlem South,East Harlem North,Manhattan,Manhattan
62,2019-03-21 23:33:55,2019-03-21 23:36:39,1,0.44,4.0,0.0,0.0,7.8,yellow,cash,Flatiron,East Chelsea,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6380,2019-03-22 19:14:43,2019-03-22 19:21:00,1,0.71,6.0,0.0,0.0,7.8,green,credit card,Marine Park/Mill Basin,Flatlands,Brooklyn,Brooklyn
6390,2019-03-19 09:32:20,2019-03-19 09:36:22,1,0.70,5.0,0.0,0.0,5.8,green,cash,Morningside Heights,Central Harlem North,Manhattan,Manhattan
6393,2019-03-10 18:33:13,2019-03-10 19:32:38,1,0.00,71.2,0.0,0.0,72.0,green,credit card,Parkchester,Flatbush/Ditmas Park,Bronx,Brooklyn
6409,2019-03-21 17:46:43,2019-03-21 17:50:46,1,0.70,5.0,0.0,0.0,6.8,green,cash,Bushwick South,Bedford,Brooklyn,Brooklyn
6415,2019-03-03 08:42:49,2019-03-03 08:46:55,1,0.89,5.0,0.0,0.0,5.8,green,cash,Washington Heights South,Washington Heights South,Manhattan,Manhattan

In [46]:
data[(data["distance"] < 1) & (data["tip"] == 0)].shape[0]

638

In [47]:
# Contoh OR: jarak < 1 mile ATAU pembayaran cash
data[(data["distance"] < 1) | (data["payment"] == "cash")]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.00,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.00,0.0,13.80,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.00,0.0,14.80,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.0,0.00,0.0,9.30,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,5.80,green,credit card,Central Park,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn

#### Catatan Penting: Hindari *Chained Indexing*

Saat kamu ingin **mengubah nilai** di DataFrame berdasarkan kondisi, jangan lakukan pola seperti ini:

```python
df[df["payment"].isna()]["payment"] = "unknown"   # ❌ berpotensi tidak bekerja / warning
```

Kenapa?
- `df[mask]` bisa menghasilkan **copy**, bukan view
- assignment-nya jadi tidak jelas nempel ke DataFrame yang mana

✅ Pola aman:
```python
mask = df["payment"].isna()
df.loc[mask, "payment"] = "unknown"
```

In [106]:
# Contoh assignment aman dengan .loc (pola yang sering dipakai)
demo = data.copy()

# Isi missing payment dengan label "unknown"
mask = demo["payment"].isna()
demo.loc[mask, "payment"] = "unknown"

demo[["payment", "pickup_zone"]].head(10)

       payment                pickup_zone
0  credit card            Lenox Hill West
1         cash      Upper West Side South
2  credit card              Alphabet City
3  credit card                  Hudson Sq
4  credit card               Midtown East
5  credit card  Times Sq/Theatre District
6  credit card          Battery Park City
7      unknown                Murray Hill
8  credit card          East Harlem South
9  credit card        Lincoln Square East

**Latihan**

Ambil **index** trip yang memenuhi kondisi ini:
- `passengers` >= 3
- `total` > 50
- `payment` == "credit card"

(Tips: bikin boolean mask dulu, lalu ambil `.index`)

## **Pandas untuk Feature Engineering (Bonus DS)**

Di Data Science, kita sering membuat fitur baru dari:
- **Text** (kolom string) → pakai accessor `.str`
- **Datetime** (kolom waktu) → pakai accessor `.dt`

Di bawah contoh kecil yang sangat umum.

### Text Ops dengan `.str` (contoh: cari keyword di zona)

Yang sering dipakai di Data Science:
- `.str.contains()` untuk filtering
- `.str.lower()` / `.str.upper()` untuk normalisasi
- `.str.split()` untuk pecah teks

Referensi resmi:
- Text data & `.str`: https://pandas.pydata.org/docs/user_guide/text.html

In [50]:
# Contoh .str untuk teks: bikin fitur "is_airport_pickup"
data_str = data.copy()

zone = data_str["pickup_zone"].fillna("")
data_str["is_airport_pickup"] = zone.str.contains("Airport", case=False, na=False)

data_str[["pickup_zone", "is_airport_pickup"]].head(10)

                 pickup_zone  is_airport_pickup
0            Lenox Hill West              False
1      Upper West Side South              False
2              Alphabet City              False
3                  Hudson Sq              False
4               Midtown East              False
5  Times Sq/Theatre District              False
6          Battery Park City              False
7                Murray Hill              False
8          East Harlem South              False
9        Lincoln Square East              False

### Datetime Ops dengan `.dt` (langsung pakai kolom `pickup`)

Dataset kita sudah punya `pickup` & `dropoff`, jadi kita bisa langsung bikin fitur waktu:
- jam (hour)
- hari (day name)
- bulan (month)

Referensi resmi:
- Time series & `.dt`: https://pandas.pydata.org/docs/user_guide/timeseries.html

In [51]:
data_time = data.copy()

data_time["pickup_hour"] = data_time["pickup"].dt.hour
data_time["pickup_day_name"] = data_time["pickup"].dt.day_name()
data_time["pickup_month"] = data_time["pickup"].dt.month

data_time[["pickup", "pickup_hour", "pickup_day_name", "pickup_month"]].head(10)

               pickup  pickup_hour pickup_day_name  pickup_month
0 2019-03-23 20:21:09           20        Saturday             3
1 2019-03-04 16:11:55           16          Monday             3
2 2019-03-27 17:53:01           17       Wednesday             3
3 2019-03-10 01:23:59            1          Sunday             3
4 2019-03-30 13:27:42           13        Saturday             3
5 2019-03-11 10:37:23           10          Monday             3
6 2019-03-26 21:07:31           21         Tuesday             3
7 2019-03-22 12:47:13           12          Friday             3
8 2019-03-23 11:48:50           11        Saturday             3
9 2019-03-08 16:18:37           16          Friday             3

## **Pandas untuk Data Cleaning**

### **Menangani Nilai Kosong dalam Data**  

Saat bekerja dengan data, sering kali kita menemukan nilai yang **kosong (NaN/Null)**.  
Untuk mendeteksi nilai kosong, kita bisa menggunakan metode `.isna()`.

In [52]:
data.isna()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6429,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6430,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6431,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6432,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [53]:
data.isna().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

#### `NaN` vs `pd.NA` (Konsep Missing Value di Pandas)

Di Pandas, missing value bisa muncul sebagai:
- `np.nan` (umumnya untuk float)
- `pd.NA` (missing value yang “universal” untuk banyak dtype modern seperti `Int64`, `string`, `boolean`)

Catatan penting:
- `pd.NA` **tidak punya nilai boolean True/False** (ambiguous), jadi jangan dipakai langsung di `if`/kondisi tanpa `isna()`.

Referensi resmi:
- Missing data: https://pandas.pydata.org/docs/user_guide/missing_data.html

In [54]:
s = pd.Series([1, pd.NA, 3], dtype="Int64")
print("Series dengan pd.NA:")
print(s)

print("\nCek missing:")
print(s.isna())

# Contoh operasi perbandingan tetap bisa (hasilnya juga bisa mengandung <NA>)
print("\nOperasi s > 1:")
print(s > 1)

Series dengan pd.NA:
0       1
1    <NA>
2       3
dtype: Int64

Cek missing:
0    False
1     True
2    False
dtype: bool

Operasi s > 1:
0    False
1     <NA>
2     True
dtype: boolean

In [56]:
# sum() akan menampilkan banyak null tiap kolom
null_per_column = data.isna().sum()     
null_per_column

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

### **Membersihkan Nilai Kosong dalam Data**  

Jika dataset mengandung nilai **kosong (NaN/Null)**, kita bisa membersihkannya menggunakan Pandas.  
Terdapat dua cara utama: **menghapus** atau **mengisi nilai kosong**.  

> Catatan: biasanya kamu **memilih salah satu** strategi (drop *atau* fill). Contoh di bawah dipisah memakai variabel baru agar `data` asli tetap aman.

In [57]:
# Contoh 1: Drop rows yang punya missing value (contoh cepat)
data_drop = data.copy()
data_drop = data_drop.dropna()
print("Shape setelah dropna:", data_drop.shape)
data_drop.isna().sum()

Shape setelah dropna: (6341, 14)

pickup             0
dropoff            0
passengers         0
distance           0
fare               0
tip                0
tolls              0
total              0
color              0
payment            0
pickup_zone        0
dropoff_zone       0
pickup_borough     0
dropoff_borough    0
dtype: int64

In [58]:
# Contoh 2: Fill missing value dengan angka 0 (contoh cepat)
# Ini cocok kalau 0 memang masuk akal (misal: jumlah transaksi yang kosong dianggap 0)
data_fill = data.copy()
data_fill = data_fill.fillna(0)
data_fill.isna().sum()

pickup             0
dropoff            0
passengers         0
distance           0
fare               0
tip                0
tolls              0
total              0
color              0
payment            0
pickup_zone        0
dropoff_zone       0
pickup_borough     0
dropoff_borough    0
dtype: int64

### **Menangani Data Duplikat**  

Terkadang, dataset mengandung **baris yang terduplikasi**, yang bisa mempengaruhi hasil analisis.  
Kita bisa menggunakan `.duplicated()` untuk mendeteksi baris yang muncul lebih dari satu kali.

In [59]:
# Dataset ini hampir tidak punya duplicate rows.
# Jadi untuk latihan, kita buat duplikat kecil secara sengaja:
df_dupes = pd.concat([data, data.sample(10, random_state=42)], ignore_index=True)
df_dupes.duplicated().sum()

10

### **Membersihkan Data Duplikat**  

Setelah mendeteksi data duplikat, kita bisa menghapusnya menggunakan `.drop_duplicates()`.

In [60]:
df_dupes_clean = df_dupes.drop_duplicates()
print("Duplikat sebelum:", df_dupes.duplicated().sum())
print("Duplikat setelah :", df_dupes_clean.duplicated().sum())

Duplikat sebelum: 10
Duplikat setelah : 0

### **Menghapus Baris & Kolom dalam DataFrame**  

Kita bisa menghapus baris atau kolom yang tidak diperlukan dalam DataFrame menggunakan `.drop()`.

In [61]:
copy_data = data.copy()
copy_data.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

#### **🔹 Parameter Utama:**  
1. **labels** → Label baris atau kolom yang ingin dihapus.  
   - Bisa berupa **satu label** atau **daftar label**.  
   - Jika menggunakan **tuple**, akan dianggap sebagai satu label, bukan daftar.  

2. **axis** → Menentukan apakah yang akan dihapus adalah **baris atau kolom**.  
   - `0` atau `'index'` → Menghapus **baris** berdasarkan label.  
   - `1` atau `'columns'` → Menghapus **kolom** berdasarkan label.  

3. **index** → Alternatif untuk menentukan baris yang dihapus.  
   - `data.drop(index=labels)` sama dengan `data.drop(labels, axis=0)`.  

4. **columns** → Alternatif untuk menentukan kolom yang dihapus.  
   - `data.drop(columns=labels)` sama dengan `data.drop(labels, axis=1)`.

In [ ]:
# Hapus beberapa kolom
copy_data.drop(columns=["color", "tolls"], inplace=True)

# Hapus beberapa baris berdasarkan index
copy_data.drop(index=[1, 3], inplace=True)

copy_data.head()

,pickup,dropoff,passengers,distance,fare,tip,total,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,12.95,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,14.16,credit card,Alphabet City,West Village,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,13.40,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,12.96,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,18.80,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan

## Materi Tambahan 
<img src="https://media.tenor.com/5z0XqvkpFEkAAAAm/betterbedricj.webp" alt="Health Points" width="200">

In [63]:
import pandas as pd

# Contoh dataset kecil untuk latihan sort + groupby (tema: penjualan kedai kopi)
data_sales = {
    "Cabang": ["Malang", "Malang", "Surabaya", "Surabaya", "Malang", "Surabaya"],
    "Produk": ["Kopi Susu", "Croissant", "Kopi Susu", "Matcha Latte", "Americano", "Croissant"],
    "Metode_Bayar": ["cash", "qris", "credit", "cash", "qris", "credit"],
    "Qty": [20, 12, 15, 9, 18, 10],
    "Harga_Rp": [18000, 17000, 18000, 22000, 16000, 17000],
}

sales_df = pd.DataFrame(data_sales)
sales_df["Revenue_Rp"] = sales_df["Qty"] * sales_df["Harga_Rp"]
sales_df

     Cabang        Produk Metode_Bayar  Qty  Harga_Rp  Revenue_Rp
0    Malang     Kopi Susu         cash   20     18000      360000
1    Malang     Croissant         qris   12     17000      204000
2  Surabaya     Kopi Susu       credit   15     18000      270000
3  Surabaya  Matcha Latte         cash    9     22000      198000
4    Malang     Americano         qris   18     16000      288000
5  Surabaya     Croissant       credit   10     17000      170000

### **Mengurutkan Data dengan `sort_values()`**  

Kita bisa mengurutkan DataFrame berdasarkan nilai dalam suatu kolom menggunakan `.sort_values()`.  
Metode ini berguna untuk melihat **peringkat tertinggi atau terendah** dalam dataset.

In [64]:
# Mengurutkan berdasarkan revenue dari yang tertinggi ke terendah
sales_df.sort_values(by="Revenue_Rp", ascending=False)

     Cabang        Produk Metode_Bayar  Qty  Harga_Rp  Revenue_Rp
0    Malang     Kopi Susu         cash   20     18000      360000
4    Malang     Americano         qris   18     16000      288000
2  Surabaya     Kopi Susu       credit   15     18000      270000
1    Malang     Croissant         qris   12     17000      204000
3  Surabaya  Matcha Latte         cash    9     22000      198000
5  Surabaya     Croissant       credit   10     17000      170000

In [65]:
# Multi-sort: Qty naik, tapi revenue turun
sales_df.sort_values(by=["Qty", "Revenue_Rp"], ascending=[True, False])

     Cabang        Produk Metode_Bayar  Qty  Harga_Rp  Revenue_Rp
3  Surabaya  Matcha Latte         cash    9     22000      198000
5  Surabaya     Croissant       credit   10     17000      170000
1    Malang     Croissant         qris   12     17000      204000
2  Surabaya     Kopi Susu       credit   15     18000      270000
4    Malang     Americano         qris   18     16000      288000
0    Malang     Kopi Susu         cash   20     18000      360000

### **GroupBy & Aggregation**  

#### **📌 Apa Itu `GroupBy`?**  
`GroupBy` adalah operasi yang memungkinkan kita untuk **mengelompokkan data** berdasarkan satu atau lebih kolom.  
Ini sangat berguna untuk melihat pola dalam dataset dengan cara mengorganisir data dalam kelompok tertentu.  

#### **📌 Apa Itu Aggregation?**  
Aggregation adalah proses **meringkas data** dengan menghitung statistik tertentu dari setiap kelompok hasil `GroupBy`.  
Contoh fungsi agregasi yang umum digunakan:  
- **`sum()`** → Menjumlahkan nilai dalam kelompok.  
- **`mean()`** → Menghitung rata-rata dalam kelompok.  
- **`count()`** → Menghitung jumlah elemen dalam kelompok.  
- **`max()` / `min()`** → Mencari nilai maksimum atau minimum dalam kelompok.

#### 📌 Cara mikir `groupby`: Split → Apply → Combine

- **Split**: data dibagi berdasarkan kategori (misal `Produk`, `Cabang`, `Metode_Bayar`)
- **Apply**: lakukan fungsi (mean/sum/count/median/...)
- **Combine**: gabungkan hasilnya jadi tabel ringkas

In [66]:
# Contoh transform: bikin kolom baru "TotalRevenuePerProduk"
df_sales = sales_df.copy()
df_sales["TotalRevenuePerProduk"] = df_sales.groupby("Produk")["Revenue_Rp"].transform("sum")
df_sales

,Cabang,Produk,Metode_Bayar,Qty,Harga_Rp,Revenue_Rp,TotalRevenuePerProduk
0,Malang,Kopi Susu,cash,20,18000,360000,630000
1,Malang,Croissant,qris,12,17000,204000,374000
2,Surabaya,Kopi Susu,credit,15,18000,270000,630000
3,Surabaya,Matcha Latte,cash,9,22000,198000,198000
4,Malang,Americano,qris,18,16000,288000,288000
5,Surabaya,Croissant,credit,10,17000,170000,374000

#### GroupBy Single Columns

In [67]:
sales_df

     Cabang        Produk Metode_Bayar  Qty  Harga_Rp  Revenue_Rp
0    Malang     Kopi Susu         cash   20     18000      360000
1    Malang     Croissant         qris   12     17000      204000
2  Surabaya     Kopi Susu       credit   15     18000      270000
3  Surabaya  Matcha Latte         cash    9     22000      198000
4    Malang     Americano         qris   18     16000      288000
5  Surabaya     Croissant       credit   10     17000      170000

In [99]:
# GroupBy berdasarkan kolom 'Produk'
grouped_by_produk = sales_df.groupby("Produk")

print(grouped_by_produk)

# Agregasi: total Qty dan rata-rata revenue per produk
aggregated = grouped_by_produk.agg(
    Total_Qty=("Qty", "sum"),
    Avg_Revenue=("Revenue_Rp", "mean"),
    Max_Revenue=("Revenue_Rp", "max"),
)

aggregated

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000189911C38E0>

              Total_Qty  Avg_Revenue  Max_Revenue
Produk
Americano            18     288000.0       288000
Croissant            22     187000.0       204000
Kopi Susu            35     315000.0       360000
Matcha Latte          9     198000.0       198000

#### GroupBy Double Columns

In [69]:
sales_df

     Cabang        Produk Metode_Bayar  Qty  Harga_Rp  Revenue_Rp
0    Malang     Kopi Susu         cash   20     18000      360000
1    Malang     Croissant         qris   12     17000      204000
2  Surabaya     Kopi Susu       credit   15     18000      270000
3  Surabaya  Matcha Latte         cash    9     22000      198000
4    Malang     Americano         qris   18     16000      288000
5  Surabaya     Croissant       credit   10     17000      170000

In [70]:
# GroupBy berdasarkan 'Cabang' dan 'Produk'
grouped = sales_df.groupby(["Cabang", "Produk"])

agg2 = grouped.agg(
    Total_Qty=("Qty", "sum"),
    Total_Revenue=("Revenue_Rp", "sum"),
    Avg_Harga=("Harga_Rp", "mean"),
)

agg2

                       Total_Qty  Total_Revenue  Avg_Harga
Cabang   Produk
Malang   Americano            18         288000    16000.0
         Croissant            12         204000    17000.0
         Kopi Susu            20         360000    18000.0
Surabaya Croissant            10         170000    17000.0
         Kopi Susu            15         270000    18000.0
         Matcha Latte          9         198000    22000.0

### **Menggunakan `.apply()` dalam Pandas**  

Metode **`.apply()`** memungkinkan kita untuk menerapkan **fungsi kustom** (_user-defined function_) pada setiap baris atau kolom dalam DataFrame.  
Ini berguna untuk melakukan operasi yang lebih kompleks daripada metode bawaan Pandas seperti `.sum()` atau `.mean()`.

In [71]:
sales_df

     Cabang        Produk Metode_Bayar  Qty  Harga_Rp  Revenue_Rp
0    Malang     Kopi Susu         cash   20     18000      360000
1    Malang     Croissant         qris   12     17000      204000
2  Surabaya     Kopi Susu       credit   15     18000      270000
3  Surabaya  Matcha Latte         cash    9     22000      198000
4    Malang     Americano         qris   18     16000      288000
5  Surabaya     Croissant       credit   10     17000      170000

In [72]:
def revenue_bucket(rev):
    if rev >= 350000:
        return "High"
    elif rev >= 250000:
        return "Medium"
    else:
        return "Low"

sales_df["Revenue_Bucket"] = sales_df["Revenue_Rp"].apply(revenue_bucket)
sales_df

,Cabang,Produk,Metode_Bayar,Qty,Harga_Rp,Revenue_Rp,Revenue_Bucket
0,Malang,Kopi Susu,cash,20,18000,360000,High
1,Malang,Croissant,qris,12,17000,204000,Low
2,Surabaya,Kopi Susu,credit,15,18000,270000,Medium
3,Surabaya,Matcha Latte,cash,9,22000,198000,Low
4,Malang,Americano,qris,18,16000,288000,Medium
5,Surabaya,Croissant,credit,10,17000,170000,Low

In [104]:
# 1) Row-wise apply (contoh) — biasanya LEBIH LAMBAT dari operasi vektorisasi
def calc_revenue_row(row):
    return row["Qty"] * row["Harga_Rp"]

sales_apply = sales_df.copy()
sales_apply["Revenue_apply"] = sales_apply.apply(calc_revenue_row, axis=1)

# Bandingkan dengan kolom Revenue_Rp yang kita buat vektorisasi
sales_apply[["Qty", "Harga_Rp", "Revenue_Rp", "Revenue_apply"]].head()

   Qty  Harga_Rp  Revenue_Rp  Revenue_apply
0   20     18000      360000         360000
1   12     17000      204000         204000
2   15     18000      270000         270000
3    9     22000      198000         198000
4   18     16000      288000         288000

In [102]:
sales_apply

,Cabang,Produk,Metode_Bayar,Qty,Harga_Rp,Revenue_Rp,Revenue_Bucket
0,Malang,Kopi Susu,cash,20,18000,360000,High
1,Malang,Croissant,qris,12,17000,204000,Low
2,Surabaya,Kopi Susu,credit,15,18000,270000,Medium
3,Surabaya,Matcha Latte,cash,9,22000,198000,Low
4,Malang,Americano,qris,18,16000,288000,Medium
5,Surabaya,Croissant,credit,10,17000,170000,Low

**Latihan**

Buat kolom `Diskon_Rp` dengan aturan:
- Kategori **Drink** → diskon 10% dari `Harga_Rp`
- Kategori **Food** → diskon 5% dari `Harga_Rp`

Lalu buat kolom `Harga_Setelah_Diskon`.

## Bonus DS: Menggabungkan Data (`concat` vs `merge`)

Kamu bakal sering ketemu kasus data kepisah di banyak tabel/file.

- `pd.concat([...])` → **numpuk** (row-wise/column-wise), cocok untuk *append dataset* yang strukturnya sama
- `pd.merge(left, right, on=...)` → **join** berdasarkan key, mirip SQL JOIN

Referensi resmi:
- Merging/Joining: https://pandas.pydata.org/docs/user_guide/merging.html

In [75]:
# Contoh concat (numpuk row)
df_a = pd.DataFrame({"id":[1,2], "score":[10,20]})
df_b = pd.DataFrame({"id":[3], "score":[30]})

concat_row = pd.concat([df_a, df_b], ignore_index=True)
print("concat row-wise:\n", concat_row)

# Contoh merge (join by key)
left = pd.DataFrame({"id":[1,2,3], "name":["A","B","C"]})
right = pd.DataFrame({"id":[1,3], "city":["Malang","Jakarta"]})

merged = pd.merge(left, right, on="id", how="left")
print("\nmerge by id (left join):\n", merged)

concat row-wise:
    id  score
0   1     10
1   2     20
2   3     30

merge by id (left join):
    id name     city
0   1    A   Malang
1   2    B      NaN
2   3    C  Jakarta

### **Menyimpan DataFrame ke File (`Saving DataFrame`)**  

Setelah mengolah data, kita bisa menyimpannya kembali dalam berbagai format seperti **CSV, Excel, atau JSON**.  
Hal ini memungkinkan kita untuk menggunakan data yang telah diproses di aplikasi lain atau untuk analisis lebih lanjut.

In [ ]:
# Menyimpan DataFrame ke dalam format CSV
sales_df.to_csv("coffee_sales.csv", index=False)

# Menyimpan DataFrame ke Excel (opsional)
# sales_df.to_excel("coffee_sales.xlsx", index=False)

print("File tersimpan: coffee_sales.csv")

File tersimpan: coffee_sales.csv

# Saatnya QnA 🤝🏻

<img src="https://media.tenor.com/1v9j5lX8I2UAAAAM/questions.gif" alt="QnA" width="220">